# Target specific macros
TARGET = program

TARGET_CPP_SOURCES = \
    program.cpp \
    driving.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./program.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../ecrobot/ecrobot++.mak
