# Target specific macros
TARGET = usb

TARGET_CPP_SOURCES = \
        program.cpp \
        ../Shared/Tools.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./program.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../ecrobot/ecrobot++.mak
